### ISSUE TITLE
"TypeError: undefined is not a function" using jasmine-server

### ISSUE THREAD

**Issue by cburgmer** [jasmine-contrib/grunt-jasmine-runner#3]
Running

```
$ ./node_modules/.bin/grunt jasmine-server
```

produces the following error.

```
$ ./node_modules/.bin/grunt jasmine-server
path.existsSync is now called `fs.existsSync`.
Running "jasmine-server" task

TypeError: undefined is not a function
    at Object.module.exports.grunt.registerHelper.jasmineCss (/Users/cburgmer/projekte/csscritic/node_modules/grunt-jasmine-runner/tasks/jasmine.js:96:5)
    at Task.helper (/Users/cburgmer/projekte/csscritic/node_modules/grunt/lib/util/task.js:117:19)
    at Object.<anonymous> (/Users/cburgmer/projekte/csscritic/node_modules/grunt-jasmine-runner/tasks/jasmine.js:52:11)
    at Object.task.registerTask.thisTask.fn (/Users/cburgmer/projekte/csscritic/node_modules/grunt/lib/grunt/task.js:56:16)
    at Task.<anonymous> (/Users/cburgmer/projekte/csscritic/node_modules/grunt/lib/util/task.js:341:36)
    at Task.start (/Users/cburgmer/projekte/csscritic/node_modules/grunt/lib/util/task.js:357:5)
    at Object.grunt.tasks (/Users/cburgmer/projekte/csscritic/node_modules/grunt/lib/grunt.js:143:8)
    at Object.module.exports [as cli] (/Users/cburgmer/projekte/csscritic/node_modules/grunt/lib/grunt/cli.js:36:9)
    at Object.<anonymous> (/Users/cburgmer/projekte/csscritic/node_modules/grunt/bin/grunt:16:14)
    at Module._compile (module.js:449:26)
```

Installed via

```
$ npm install grunt-jasmine-runner
```

**Comment by jsoverson** [comment]
Thanks, fixed in source. Missed a check for a valid callback.
